// File generated by FlutterFire CLI & configured for Belagavi Property.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9R_7VhpeVi4mS5fzWS0vYjG5kNmQ9Aa0',
    appId: '1:1031008602596:web:be9fe1eba89f9a991e5ff1',
    messagingSenderId: '1031008602596',
    projectId: 'belagavi-property',
    authDomain: 'belagavi-property.firebaseapp.com',
    storageBucket: 'belagavi-property.firebasestorage.app',
    measurementId: 'G-KHNFPMGP9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQghhpxMGfk9d2B-cihxEw0wKep8Eo24E',
    appId: '1:1031008602596:android:771ba8306602e04d1e5ff1',
    messagingSenderId: '1031008602596',
    projectId: 'belagavi-property',
    storageBucket: 'belagavi-property.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgdnI1BVwQGnXkqDTYTr6nI2eud736I10',
    appId: '1:1031008602596:ios:b021b1ff1b178e7b1e5ff1',
    messagingSenderId: '1031008602596',
    projectId: 'belagavi-property',
    authDomain: 'belagavi-property.firebaseapp.com',
    storageBucket: 'belagavi-property.firebasestorage.app',
    iosBundleId: 'com.belagavi.belagaviProperty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgdnI1BVwQGnXkqDTYTr6nI2eud736I10',
    appId: '1:1031008602596:ios:b021b1ff1b178e7b1e5ff1',
    messagingSenderId: '1031008602596',
    projectId: 'belagavi-property',
    authDomain: 'belagavi-property.firebaseapp.com',
    storageBucket: 'belagavi-property.firebasestorage.app',
    iosBundleId: 'com.belagavi.belagaviProperty',
  );
}
